name: 'games_elt'
version: '1.0.0'
config-version: 2

profile: 'games_elt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  games_elt:
    staging:
      +materialized: table
      +schema: STAGING
    modeling:
      +materialized: incremental
      +schema: MODELED_DATA
      dim_date:
        table: dim_date
      fct_game:
        table: fct_game
      dim_opening:
        table: dim_opening
      dim_user:
        table: dim_result
